<?php
$namafile='Laporan_Laba_Rugi_Bordir_'.date('YmdHis');
header("Content-type: application/vnd-ms-excel");
header("Content-Disposition: attachment; filename=".$namafile.".xls");
?>
<table border="1" style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th colspan="2" style="background-color: #e2efda; height: 30px;"><b>LAPORAN LABA - RUGI BORDIR FORBOYS</b></th>
        </tr>
        <tr>
            <th colspan="2" style="background-color: #e2efda;">Periode: <?php echo date('d/m/Y', strtotime($tanggal1)); ?> - <?php echo date('d/m/Y', strtotime($tanggal2)); ?></th>
        </tr>
        <tr>
            <th style="background-color: #fce4d6; width: 300px;">KATEGORI</th>
            <th style="background-color: #fce4d6; width: 150px;">NOMINAL (RP)</th>
        </tr>
    </thead>
    <tbody>
        <!-- PENDAPATAN -->
        <tr>
            <td style="background-color: #d9e1f2;"><b>PENDAPATAN</b></td>
            <td style="background-color: #d9e1f2;"></td>
        </tr>
        <tr>
            <td>Pendapatan PO Dalam</td>
            <td align="right"><?php echo $totalpendapatan; ?></td>
        </tr>
        <tr>
            <td>Pendapatan PO Luar / PO Homie</td>
            <td align="right"><?php echo $totalpoluar; ?></td>
        </tr>
        <tr style="background-color: #fff2cc;">
            <td><b>TOTAL PENDAPATAN</b></td>
            <td align="right"><b><?php echo $pend; ?></b></td>
        </tr>

        <!-- Jarak -->
        <tr>
            <td colspan="2" style="height: 20px;"></td>
        </tr>

        <!-- PENGELUARAN -->
        <tr>
            <td style="background-color: #f8cbad;"><b>PENGELUARAN</b></td>
            <td style="background-color: #f8cbad;"></td>
        </tr>
        <tr>
            <td>Belanja Bordir</td>
            <td align="right"><?php echo $belanjabordir; ?></td>
        </tr>
        <tr>
            <td>Gaji Operator Bordir <?php if (!empty($tgl_sabtu) && !empty($tgl_jumat)) { ?>(Periode <?php echo date('d/m/Y', strtotime($tgl_sabtu)) ?> - <?php echo date('d/m/Y', strtotime($tgl_jumat)) ?>)<?php } ?></td>
            <td align="right"><?php echo isset($gajioperator) ? $gajioperator : (isset($gajibordir) ? $gajibordir : 0); ?></td>
        </tr>
        <tr>
            <td>Gaji Buang Benang Bordir <?php if (!empty($tgl_sabtu) && !empty($tgl_jumat)) { ?>(Periode <?php echo date('d/m/Y', strtotime($tgl_sabtu)) ?> - <?php echo date('d/m/Y', strtotime($tgl_jumat)) ?>)<?php } ?></td>
            <td align="right"><?php echo isset($gajibuangbenang) ? $gajibuangbenang : 0; ?></td>
        </tr>
        <tr>
            <td>Gaji Bulanan Bordir</td>
            <td align="right"><?php echo isset($gajibulanan) ? $gajibulanan : 0; ?></td>
        </tr>
        <tr>
            <td>Kasbon Karyawan Bordir</td>
            <td align="right"><?php echo isset($kasbon) ? $kasbon : 0; ?></td>
        </tr>
        <tr>
            <td>Operasional (BBM, Service, Fotokopi)</td>
            <td align="right"><?php echo $operasional; ?></td>
        </tr>
        <tr>
            <td>Service (Mesin Bordir)</td>
            <td align="right"><?php echo $service; ?></td>
        </tr>
        <tr>
            <td>Potongan Warteg</td>
            <td align="right"><?php echo isset($potonganwarteg) ? $potonganwarteg : 0; ?></td>
        </tr>
        <?php $totalpengeluaran = ($belanjabordir + (isset($gajioperator) ? $gajioperator : (isset($gajibordir) ? $gajibordir : 0)) + (isset($gajibuangbenang) ? $gajibuangbenang : 0) + (isset($gajibulanan) ? $gajibulanan : 0) + (isset($kasbon) ? $kasbon : 0) + $operasional + $service + (isset($potonganwarteg) ? $potonganwarteg : 0)); ?>
        <tr style="background-color: #fff2cc;">
            <td><b>TOTAL PENGELUARAN</b></td>
            <td align="right"><b><?php echo $totalpengeluaran; ?></b></td>
        </tr>

        <!-- Jarak -->
        <tr>
            <td colspan="2" style="height: 20px;"></td>
        </tr>

        <!-- SUMMARY -->
        <tr style="background-color: #bdd7ee; height: 35px;">
            <td style="font-size: 14px;"><b>LABA PRODUKSI (BERSIH)</b></td>
            <td align="right" style="font-size: 14px;"><b><?php echo ($pend - $totalpengeluaran); ?></b></td>
        </tr>
    </tbody>
</table>
<br>
<p style="font-size: 10px;"><i>Generated by Forboys Production System at <?php echo date('d-m-Y H:i:s'); ?></i></p>